# Generated by Django 5.0 on 2023-12-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='files/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='KnownFace',
        ),
    ]
